routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeglareController@getHome');
Route::get('/home', 'HomeglareController@getHome');
Route::get('/about', 'HomeglareController@getAbout');
Route::get('/sell-on-homeglare', 'HomeglareController@getSeller');
Route::post('/offer-detail', 'HomeglareController@getOfferDetail');
Route::get('/cart/{id}', 'HomeglareController@getCart');
Route::get('/checkout/{id}', 'HomeglareController@getCheckout');
Route::get('/contact', 'HomeglareController@getContact');
Route::get('/faq', 'HomeglareController@getFaq');
Route::get('/account/{id}', 'HomeglareController@getAccount');
Route::get('/product-detail/{slug}', 'HomeglareController@getProductDetails');
Route::get('/product/{slug}', 'HomeglareController@getProducts');
Route::get('/register', 'HomeglareController@getRegister');
Route::get('/wishlist/{id}', 'HomeglareController@getWishlist');


// Route::get('event', 'PayController@index');
 Route::post('pay', 'PayController@pay');
 Route::get('pay-success', 'PayController@success');


Route::get('/auth/redirect/facebook', 'SocialController@redirect');
Route::get('/callback/facebook', 'SocialController@callback');

Route::get('/redirect/google', 'SocialAuthGoogleController@redirect');
Route::get('/callback/google', 'SocialAuthGoogleController@callback');

Route::post('/add-to-cart','AjaxController@addToCart');
Route::post('/add-to-wishlist','AjaxController@addToWishlist');
Route::post('/delete-wishlist-item','AjaxController@deleteWishlistItem');
// Route::post('/newsletter','AjaxController@submitNewsletter');
Route::post('/newsletter', 'SiteController@createNewsletter')->name('newsletter');
Route::post('/cart/delete-product/{id}','AjaxController@deleteSessionData');
// Route::post('/cart/delete-product','AjaxController@deleteSessionData');
Route::post('/update-cart','AjaxController@updateCart');

Auth::routes();

Route::get('/home', 'HomeglareController@getHome');
Route::get('/', 'HomeglareController@getHome');
Route::post('/update-password', 'AjaxController@updatePassword');
Route::post('/update-profile', 'AjaxController@updateProfile');
// Route::get('/','SiteController@getIndex');
// Route::get('/home', 'SiteController@getIndex')->name('home');
// Route::get('/product-detail/{slug}','SiteController@getProductDetail');
// Route::get('/products/{slug}','SiteController@getCategoryProducts');

// Route::get('/searched-producs/{id}/{keyword}','SiteController@getSearchedProducts');
// Route::get('/cart/{id}','SiteController@getCart');
// Route::get('/checkout/{id}','SiteController@getCheckoutPage');
Route::post('/order-product', 'SiteController@orderProduct')->name('order-product');
Route::get('/order-booked', function()
{
  return view('homeglare2.ordersuccess');
});
// Route::get('/wishlist/{id}','SiteController@getWishlist');
Route::get('/about-us','SiteController@getAboutUs');
Route::get('/contact','SiteController@getContactUs');
Route::post('/contact-us', 'SiteController@contactUs')->name('contact-us');
Route::get('/faq','SiteController@getFaq')->name('faq');
Route::get('/terms&conditions','SiteController@getTermsandCondition');
Route::get('/privacy-policy','SiteController@getPrivacyPolicy');
Route::get('/return-policy','SiteController@getReturnPolicy');
Route::get('/my-account/{id}','SiteController@getMyAccount');
Route::get('/ordered-item-details/{order_id}', 'SiteController@orderedItemDetails')->name('ordered-item-details');
Route::get('/ordered-item-track/{order_id}', 'SiteController@orderedItemTrack')->name('ordered-item-track');
Route::resource('reply', 'ReplyController');

Route::get('/show-minicart','AjaxController@showMiniCart');
Route::get('/search-product/productsCat','AjaxController@showProductCat');
Route::get('/search-product/sort', 'AjaxController@sorting');
Route::get('/search-product/price-filter', 'AjaxController@price');
Route::get('/search-product/colored', 'AjaxController@colored');
Route::get('/search-product/rating', 'AjaxController@rating');
Route::resource('help-support', 'HelpSupportController');

Route::get('/get-product_details-data/{productId}', 'AjaxController@getProductDetailsData');
Route::post('/give-product-rating', 'SiteController@giveProductRating')->name('give-product-rating');
Route::post('/global-search-product', 'SiteController@globalSearchProduct')->name('global-search-product');

// snapSocialShare
Route::get('/shareLinkOnSocialSite/{siteKey}/{slug_url}/{product_id}', 'SiteController@shareLinkOnSocialSite');
//fb snap Social Share callback
Route::get('SharedLink/callback/{siteKey}', 'SiteController@SharedLinkCallback');

app/Http/Controllers/HomeglareController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Models\Address;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Review;
use App\Wishlist;
use App\Models\Offer;
use App\Models\Banner;
use App\Models\Company;
use App\Models\Query;
use App\Models\Faq;
use App\Models\Newsletter;
use App\Models\Help;
use Log;
use DB;
use Auth;
use Mail;

class HomeglareController extends Controller
{
	public function getHome(){
		$companyInfo = Company::first();
		$maincategory = Category::where('status','Active')->where('category_id',0)->get();
		$slider_cat = Category::where('status','Active')->where('category_id',0)->orderBy('created_at','DESC')->limit(5)->get();
		$slider_banners = Banner::where('image_type','slider')->where('status','Active')->get();
		
		$medium_banners = Banner::where('image_type','medium')->where('status','Active')->get();

		$featured_products = Product::where('trending','yes')->orderBy('created_at','DESC')->limit(25)->get();
		$new_products = Product::orderBy('name','ASC')->orderBy('created_at','DESC')->limit(25)->get();
		$trending_products = Product::orderBy('created_at','DESC')->limit(3)->get();
		
		$offers = Offer::where('status','Active')->orderBy('created_at','DESC')->limit(3)->get();
		
		return view('homeglare2.home', compact('companyInfo','maincategory','slider_banners', 'medium_banners','featured_products','new_products','offers','slider_cat','trending_products'));
		// return view('homeglare2.home',compact('companyInfo'));
	}

	public function getAbout(){
		return view('homeglare2.about-us');
	}

	public function getCart(){
		return view('homeglare2.cart');
	}

	public function getCheckout(){
		$productDetails = array();
  $totalAmount = 0;
  if (session()->get('cart')) {
    foreach (session()->get('cart') as $key => $value) {
      $product = Product::where('id', $value->product_id)->first();
      $product['quantity'] = $value->quantity;
      $product['total_price'] = $product->sell_price * $value->quantity;
      $totalAmount += $product['total_price'];
      array_push($productDetails, $product);
    }
  } else {
    return redirect('/');
  }

  $success ='';
  $address = Address::where('user_id', Auth::user()->id)->first();
  if(isset($address))
  $allAddress = Address::where('user_id', Auth::user()->id)->where('id','!=',$address->id)->get();
else
	$allAddress="";

      // Log::info($address);
  return view('homeglare2.checkout', compact('productDetails', 'totalAmount', 'success', 'address', 'allAddress'));
		
	}

	public function getContact(){
		 $companyInfo = Company::first();
		return view('homeglare2.contact',compact('companyInfo'));
	}

	public function getFaq(){
		return view('homeglare2.faq');
	}

	public function getLogin(){
		return view('homeglare2.login');
	}

	public function getAccount(){
		$user = Auth::user();
  $addresses = "";
  $orderDetails = Order::where('user_id', $user->id)->where('status','order_booked')->get();
  $address = Address::where('user_id', $user->id)->first();
   $upd_add = Address::where('user_id', $user->id)->first();
  
  if(!empty($address))
  $addresses = Address::where('user_id', $user->id)->where('id','!=',$address->id)->get();
  $help = Help::where('user_id', $user->id)->get();
  // return view('homeglare.my-account', compact('user', 'orderDetails', 'address', 'help','addresses'));
		return view('homeglare2.my-account', compact('user', 'orderDetails', 'address', 'help','addresses','upd_add'));
	}

	public function getProductDetails(Request $request,$slug){
		$product = Product::where('slug',$slug)->first();
		$category = Category::where('id',$product->category_id)->first();
		$related_products = Product::where('category_id',$product->category_id)->get();
		$productReview = Review::where('product_id', $product->id)->avg('rating');
$countReview = Review::where('product_id', $product->id)->count();

$productReview = floor($productReview);
$reviews = Review::where('product_id',$product->id)->get();
		return view('homeglare2.product-details',compact('product','category','related_products','productReview','countReview','reviews'));
	}

	public function getProducts($id,Request $request){
		$checkId = Category::where('slug',$id)->first();
		$subcat = $checkId->id;

		$keyword = $request->product_keyword;
		$max_price = Product::where('status','Active')->max("sell_price");

		$cartproducts = array();
		$color = array();
		$brand = array();
		$material = array();
		$size = array();
		$quantity = array();
		$cnt = 0;
		if(session()->get('cart') != null){
			foreach(session()->get('cart') as $cart){
				$cartproducts[$cnt] = Product::where('id',$cart->product_id)->first();
				$quantity[$cnt] = $cart->quantity;
				$cnt++;
			}
		}
		else{
			$cartproducts = null;
			$quantity = 0;
		}

		$lastproduct = Product::where('status','Active')->orderBy('created_at','desc')->first();

		$maincategory = Category::where('category_id',0)->where('status','Active')->get();

		foreach($maincategory as $row){
			$count=0;
			$count=Product::where('category_id',$row->id)->where('status','Active')->count();
			$category = Category::where('category_id',$row->id)->where('status','Active')->get();
			if($category){
				foreach($category as $col){
					$count+=Product::where('category_id',$col->id)->where('status','Active')->count();
					$subcategory = Category::where('category_id',$col->id)->where('status','Active')->get();
					if($subcategory){
						foreach($subcategory as $set){
							$count+=Product::where('category_id',$set->id)->where('status','Active')->count();
						}
					}
				}
			}
		}

		$searched_products = array();
		$cat_ids = array();

		$total = array();
		$i=0;
		$sec = Category::where('slug',$id)->where('status','Active')->first();
		$cat_ids[0] = Category::where('id',$sec->id)->where('status','Active')->first();

		$cid = 1;
		$cnt_pro = 0;
		$count_catpro = 0;
		$idss = Category::where('category_id',$sec->id)->where('status','Active')->get();
		if($idss != null){
			foreach($idss as $ids){
				$count_catpro = 0;
				$cat_ids[$cid++] = $ids;
				$idsss = Category::where('category_id',$ids->id)->where('status','Active')->get();
				$count_catpro+=Product::where('category_id',$ids->id)->where('status','Active')->count();
				if($idsss != null){
					foreach($idsss as $ds){
						$cat_ids[$cid++] = $ds;
						$count_catpro+=Product::where('category_id',$ds->id)->where('status','Active')->count();
					}
					if($count==0)
						$total[$i++] = 0;
					else
						$total[$i++] = $count_catpro;
				}
			}
		}

		for($j=0 ; $j<$cid ; $j++){
			$products = Product::where('category_id',$cat_ids[$j]->id)->where('status','Active')->get();
			if($products != null){
				foreach($products as $pro){
					$searched_products[$cnt_pro] = $pro;
					$color[$cnt_pro] = $pro->product_color;
					$brand[$cnt_pro] = $pro->product_brand;
					$material[$cnt_pro] = $pro->product_material;
					$cnt_pro++;
				}
			}
		}

		$color = array_filter($color);
		$color = array_unique($color);

		$brand = array_filter($brand);
		$brand = array_unique($brand);

		$material = array_filter($material);
		$material = array_unique($material);

		shuffle($searched_products);

		return view('homeglare2.product',compact('maincategory','searched_products','cat_ids','total','lastproduct','max_price','cartproducts','quantity','id','color','brand','material'));
	}

	public function getRegister(){
		return view('homeglare2.register');
	}


	public function getWishlist(Request $request, $id){
		$wishlist = Wishlist::where('user_id',$id)->get();

  return view('homeglare2.wishlist',compact('wishlist'));
		
	}
	
	public function getSeller(){
		$offers = Offer::where('status','Active')->orderBy('created_at','DESC')->get();
		return view('homeglare2.seller',compact('offers'));
	}

	public function getOfferDetail(Request $request){
		$id = $request->id;
		$offer = Offer::find($id);
		return response()->json(['offer'=>$offer]);
	}

}

resources/views/homeglare/404.blade.php
@extends('layouts/ecommerce')

@section('content')
        <!-- Begin Hiraola's Breadcrumb Area -->
        <!-- <div class="breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-content">
                    <h2>Other</h2>
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li class="active">Error 404</li>
                    </ul>
                </div>
            </div>
        </div> -->
        <!-- Hiraola's Breadcrumb Area End Here -->
        <!-- Begin Hiraola's Error 404 Page Area -->
        <div class="error404-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 ml-auto mr-auto text-center">
                        <div class="search-error-wrapper">
                            <h1>404</h1>
                            <h2>PAGE NOT BE FOUND</h2>
                            <p class="short_desc">Sorry but the page you are looking for does not exist, have been removed, name
                                changed or is temporarily unavailable.</p>
                            <form action="javascript:void(0)" class="error-form">
                                <div class="inner-error_form">
                                    <input type="text" placeholder="Search..." class="error-input-text">
                                    <button type="submit" class="error-search_btn"><i class="fa fa-search"></i></button>
                                </div>
                            </form>
                            <div class="hiraola-btn-ps_center"></div>
                            <a href="/" class="hiraola-error_btn">Back To Home Page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hiraola's Error 404 Page End Here -->

       @endsection

resources/views/homeglare/about-us.blade.php
@extends('layouts/ecommerce')

@section('content')
        <!-- Begin Hiraola's About Us Area -->
        <div class="about-us-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 d-flex align-items-center">
                        <div class="overview-content">
                            @if($aboutCompany)
                              <h2><span>About Us</span></h2>
                              <p class="short_desc"><?php echo $aboutCompany->about_us; ?> </p>
                            @else
                            <h2>Welcome To <span>{{env('APP_NAME')}}</span></h2>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/homeglare/event.blade.php
@extends('layouts.homeglare')

@section('content')
<div class="container">
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
  	
<div class="row">
    <div class="col-lg-12 ">
        <div class="card-header" style="background: #eee;margin-top: 40px">
            <h2>Customer Info</h2>
        </div>
    </div>
</div>
<br><br>
     
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Opps!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
     
<form action="{{ url('pay') }}" method="POST" name="laravel_instamojo">
    {{ csrf_field() }}
               
     <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <strong>Name</strong>
                <input type="text" name="name" class="form-control" placeholder="Enter Name" required value="{{$user->name}}">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Mobile Number</strong>
                <input type="text" name="mobile_number" class="form-control" placeholder="Enter Mobile Number" required value="{{$phone}}">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Email Id</strong>
                <input type="text" name="email" class="form-control" placeholder="Enter Email id" required value="{{$user->email}}">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Payable Amount</strong>
                <input type="text" name="amount" class="form-control" placeholder="" readonly="" value="{{$amount}}">
            </div>
        </div>
        <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
     
</form>
</div>
</div>
</div>



@endsection

resources/views/homeglare/faq.blade.php
@extends('layouts/ecommerce')

@section('content')


        <!-- Begin Hiraola's Breadcrumb Area -->
        <!-- <div class="breadcrumb-area">
            <div class="container">
                <div class="breadcrumb-content">
                    <h2>Other</h2>
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li class="active">FAQ</li>
                    </ul>
                </div>
            </div>
        </div> -->
        <!-- Hiraola's Breadcrumb Area End Here -->
        <!-- Begin Hiraola's Frequently Area -->
        <div class="frequently-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="frequently-content">
                            <div class="frequently-desc">
                                <h3>Below are frequently asked questions, you may find the answer for yourself</h3>
                                <p></p>
                            </div>
                        </div>
                        
                        <!-- Begin Frequently Accordin -->
                        <div class="frequently-accordion">
                            <div id="accordion">
                                @if($faq)
                                  @foreach($faq as $index => $faqData)
                                  <div class="card {{$index == 0 ? 'actives': ''}}">
                                      <div class="card-header" id="heading{{$index}}">
                                          <h5 class="mb-0">
                                              <a href="javascript:void(0)" class="{{$index > 0 ? 'collapsed': ''}}" data-toggle="collapse" data-target="#collapse{{$index}}" aria-expanded="true" aria-controls="collapse{{$index}}">
                                                  {{$faqData->question}}
                                              </a>
                                          </h5>
                                      </div>
                                      <div id="collapse{{$index}}" class="collapse {{$index == 0 ? 'show': ''}}" aria-labelledby="heading{{$index}}" data-parent="#accordion">
                                          <div class="card-body">
                                            {{$faqData->answer}}
                                          </div>
                                      </div>
                                  </div>
                                  @endforeach
                                @endif
                            </div>
                        </div>
                        <!--Frequently Accordin End Here -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Hiraola's Frequently Area End Here -->

@endsection

resources/views/homeglare/help-support.blade.php
@extends('layouts/ecommerce')

@section('content')
      <main class="page-content">
        <div class="account-page-area">
          <div class="container">
            <div class="row">
              <div class="col-12">
                <h3 class="contact-page-title text-center mb-2">Help Support</h3>
                <form method="post" action="{{ route('help-support.store') }}">
                     {{ csrf_field() }}
                   <div class="form-group row">
                     <label for="subject" class="col-sm-2 col-form-label">Subject</label>
                     <div class="col-sm-10">
                       <!-- <input type="text" class="form-control" name="subject" id="subject" placeholder=""> -->
                       <select class="custom-select @error('service_name') is-invalid @enderror" name="subject" id="subject"  value="{{ old('subject') }}" required autocomplete="subject" autofocus>
                         <option value="" class="d-none">Select subject</option>
                         <option value="regarding_payment">Regarding Payment</option>
                         <option value="regarding_order">Regarding Order</option>
                         <option value="regarding_cancellation">Regarding Cancellation</option>
                         <option value="other_subject">Other</option>
                       </select>
                       @error('subject')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                     </div>

                   </div>
                   @if($allOrders)
                   <div class="form-group row">
                     <label for="order_id" class="col-sm-2 col-form-label">Order ID</label>
                     <div class="col-sm-10">
                       <!-- <input type="text" class="form-control" name="subject" id="subject" placeholder=""> -->
                       <select class="custom-select @error('order_id') is-invalid @enderror" name="order_id" id="order_id"  value="{{ old('order_id') }}" autocomplete="order_id" autofocus>
                         <option value="" class="d-none">Select Order</option>
                         @foreach($allOrders as $orders)
                         <option value="{{$orders->id}}">{{$orders->id}}</option>
                         @endforeach
                       </select>
                       @error('subject')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                     </div>

                   </div>
                   @endif

                   <div class="form-group row d-none" id="other">
                     <label for="other_subject" class="col-sm-2 col-form-label">Other Subject </label>
                     <div class="col-sm-10">
                       <input type="text" class="form-control" name="other_subject" id="other_subject" placeholder="Other Subject">
                     </div>
                   </div>

                   <div class="form-group row">
                     <label for="document" class="col-sm-2 col-form-label">Document</label>
                     <div class="col-sm-10">
                       <input id="document" type="file" class="form-control-file @error('document') is-invalid @enderror" name="document" value="{{ old('document') }}" autocomplete="document" autofocus>

                        @error('document')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                     </div>
                   </div>

                   <div class="form-group row">
                     <label for="message_content" class="col-sm-2 col-form-label">Your Message</label>
                     <div class="col-sm-10">
                       <textarea rows="4" cols="40" class="form-control @error('message_content') is-invalid @enderror" name="message_content" id="message_content" placeholder="Your Query">{{old('message_content')}}</textarea>
                       @error('message_content')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                     </div>
                   </div>

                  <div class="form-group row">
                    <div class="col-sm-10">
                      <button type="submit" class="btn btn-primary">Submit Request</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
@endsection

resources/views/homeglare/minicart.blade.php
<?php
use App\Review;
$total = 0;
?>
<!-- <div class="row">
  <div class="col-md-6">
    <div class="">
      <h4>Shopping Cart</h4>
    </div>
  </div>
  <div class="col-md-6">
    <a href="#" class="btn-close"><i class="ion-android-close"></i></a>
  </div>
</div> -->

<div class="offcanvas-minicart_wrapper">
          <div class="offcanvas-menu-inner">
            <a href="javascript:void(0);" id="minicartA" class="btn-close"><i class="ion-android-close"></i></a>
            <div class="minicart-content">
              <div class="minicart-heading">
                <h4>Shopping Cart</h4>
              </div>
              @if($cartproducts != null)
                <?php $i=0;  ?>
              <ul class="minicart-list">
                @foreach($cartproducts as $product)

                <li class="minicart-product" id="listhide{{$product->id}}">
                  <a class="product-item_remove" href="javascript:void(0)"  onclick="deleteProduct({{$product->id}})"><i class="ion-android-close"></i></a>
                  <div class="product-item_img">
                    <img src="{{url('/')}}/{{$product->image1}}" alt="Hiraola's Product Image">
                  </div>
                  <div class="product-item_content">
                    <a class="product-item_title" href="/product-detail/{{$product->slug}}">{{strtoupper($product->name)}}</a>
                    <span class="product-item_quantity">{{$quantity[$i]}} x Rs. {{$product->sell_price}}</span>
                  </div>
                </li>
                <?php
                      $total  =$total + $product->sell_price * $quantity[$i];
                      $i++;
                      ?>
                @endforeach
              </ul>
              @endif
            </div>
            <div class="minicart-item_total">
              <span>Subtotal</span>
              <span class="ammount">Rs. <p id="total-bill">{{$total}}</p></span>
            </div>
            <div class="minicart-btn_area">
              <a href="<?php if(!empty(Auth::user()->id)){echo '/cart/'.Auth::user()->id;} else{ echo '/login'; } ?>" class="hiraola-btn hiraola-btn_dark hiraola-btn_fullwidth">Cart</a>
            </div>
            <div class="minicart-btn_area">
              <a href="<?php if(!empty(Auth::user()->id)){echo '/checkout/'.Auth::user()->id;} else{ echo '/login'; } ?>" class="hiraola-btn hiraola-btn_dark hiraola-btn_fullwidth">Checkout</a>
            </div>
          </div>
        </div>



        <script type="text/javascript">
          $("#minicartA").on("click", function(){
            $("#miniCart").removeClass('open');
          });
        </script>

resources/views/homeglare/reply.blade.php
@extends('layouts/ecommerce')

@section('content')
      <main class="page-content">
        <div class="account-page-area">
          <div class="container">
            @if($helpSupport)
            <div class="row">
              <div class="col-12">
                <h3 class="contact-page-title text-center mb-2">Subject : {{$helpSupport->subject}}</h3>
                @if($replyMessages)
                @foreach($replyMessages as $reply)
                <div class="row justify-content-end">
                  <div class="col offset-md-8">
                    <p class="d-block badge badge-pill {{$reply->reply_from == 'admin' ? 'float-left badge-success' : 'float-right badge-info'}}">{{$reply->message}}</p>
                  </div>
                </div>
                @endforeach

                @endif
                <form method="post" action="{{ route('reply.store') }}">
                     {{ csrf_field() }}
                     <input type="text" name="token" value="{{$helpSupport->token}}" hidden>
                     <div class="form-group row justify-content-end">
                       <label for="message_content" class="col-sm-2 offset-md-6 col-form-label"></label>
                       <div class="col-sm-4">
                         <textarea rows="4" cols="40" class="form-control @error('message_content') is-invalid @enderror" name="message_content" id="message_content" placeholder="Your Query" required>{{old('message_content')}}</textarea>
                         @error('message_content')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                       </div>
                     </div>

                  <div class="form-group row float-right">
                    <div class="col ">
                      <button type="submit" class="btn btn-primary">Send</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            @else
              <h4 class="badge badge-pill badge-danger">Something Went Wrong</h4>
            @endif
          </div>
        </div>
      </main>
@endsection

resources/views/homeglare/terms.blade.php
@extends('layouts.ecommerce')

@section('content')

@endsection